sudo: required
services:
    - docker

before_install:
    - docker build . -t natdanaimungkung/docker-react

# script:
#     - docker run -e CI=true  natdanaimungkung/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket-name: "elasticbeanstalk-us-east-2-389486705749"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY